name: integration-tests
description: "Run integration tests"

runs:
  using: "composite"
  steps:
    - name: "Get the emojivoto list, should returns 200"
      shell: bash
      run: |
        status_code=$(curl --write-out %{http_code} --silent --output /dev/null http://emojivoto.aglez.k736.net/api/list)
				if [[ "$status_code" -ne 200 ]] ; then echo exit 1; else exit 0; fi
    - name: "Vote Doughnut, should returns 200"
      shell: bash
      run: |
        status_code=$(curl --write-out %{http_code} --silent --output /dev/null http://emojivoto.aglez.k736.net/api/vote?choice=:doughnut:)
				if [[ "$status_code" -ne 200 ]] ; then echo exit 1; else exit 0; fi
